version: '3.8'
services:
  app:
    container_name: nodejs-app
    build:
      context: ./demo_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=mydatabase
    depends_on:
      - db
    volumes:
      - ./demo_app:/app\
     # - ./node_modules:/app/node_modules
    command: /bin/sh -c "sleep 10;  npm run migrate; npm run seed;  npm start"


  db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: